name: Build And Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-python-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analyse code with pylint
      id: Python-App-Linting
      run: |
        find . -name '*.py' -exec pylint {} \;
    - name: Unit Testing
      id: Testing-Python-Application
      run: |
        python tests.py

    
    - name: Python Application Build Notification
      uses: act10ns/slack@v1
      with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
      if: always()
      env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}





  build-docker-app:

    runs-on: ubuntu-latest
    needs: 
      - build-python-app
    steps:
    - name: Checkout
      id: Checkout
      uses: actions/checkout@v2
      
    - name: Lint Dockerfile
      id: Lint-the-Dockerfile
      uses: hadolint/hadolint-action@v1.4.0
      with:
        dockerfile: Dockerfile
    - name: Build the Docker image
      id: Build-the-Docker-image
      run: docker build . --file Dockerfile --tag file-system-server:$(date +%s)

    - name: Docker Application Build Notification
      uses: act10ns/slack@v1
      with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
      if: always()
      env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  
        
          



      



    
